TARGET := iphone:clang:latest:14.0
INSTALL_TARGET_PROCESSES = UIKit

include $(THEOS)/makefiles/common.mk
TWEAK_NAME = ManaBoxCrack
ManaBoxCrack_FILES = Tweak.xm
ManaBoxCrack_FRAMEWORKS = UIKit Foundation
include $(THEOS_MAKE_PATH)/tweak.mk
